//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int Id { get; set; }
        public string BorrowerList { get; set; }
        public bool Disable { get; set; }
        public string AspNetUserId { get; set; }
        public int RoomId { get; set; }
        public int SessionNo { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
